// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


throw {
      RE_EXN_ID: "Match_failure",
      _1: [
        "Demo.re",
        8,
        2
      ],
      Error: new Error()
    };

exports.decision = decision;
exports.resonse = resonse;
exports.div = div;
/* resonse Not a pure module */
